In [4]:
#Import the libraries needed to run the code
import pandas as pd
import sqlalchemy as sa
import plotly.express as px
import plotly.graph_objects as go
from sqlalchemy.engine import create_engine

In [7]:
import pandas as pd

pd.read_sql("SHOW TABLES;", engine)

  Tables_in_hplussport
0             Customer
1            OrderItem
2               Orders
3              Product
4          Salesperson

In [5]:
# Connecting to the HPlusSport database
engine = create_engine("mysql+pymysql://mariadb:mariadb@localhost/hplussport?charset=utf8mb4")
connection = engine.connect()

In [8]:
#Let's take a peak at our data. This code shows the first 5 records
df = pd.read_sql_query("SELECT * FROM Orders",
                       connection)
df.head()

   OrderID CreationDate  TotalDue    Status  CustomerID  SalespersonID
0     1000   2016-05-14    118.22      paid         413            130
1     1001   2016-07-31    211.22  returned         128            102
2     1002   2016-07-09    139.81  past due         791            115
3     1003   2016-04-04    323.71      paid         974            139
4     1004   2016-02-16    214.02      paid         866            102

In [11]:
print(df.columns)

Index(['OrderID', 'CreationDate', 'TotalDue', 'Status', 'CustomerID',
       'SalespersonID'],
      dtype='str')

In [ ]:
# Create a Web-based Dashboard using Dash
import dash
from dash import dcc
from dash import html

fig = go.Figure()

for index, row in df.iterrows():
    df_salesperson = df[df['Salesperson'] == row.Salesperson]
    fig.add_trace(
        go.Scatter(x=list(df_salesperson.OrderDate),
               y=list(df_salesperson['Total Due']),
               name=row.Salesperson,
               text=list(df['Total Due'].round(1)),
               textposition="top left"))

salesperson_list = []
visibility = [False for i in range(len(df['Salesperson']))]
for index, row in df.iterrows():
    visibility = [False for i in range(len(df['Salesperson']))]
    visibility[index] = True
    d = dict(label=row.Salesperson,
          method="update",
        args=[{"visible": visibility},
               {"title": "Order Summary",
                "annotations": []}])

    salesperson_list.append(d)
    

fig.update_layout(
    updatemenus=[
        dict(
            active=0,
            buttons=salesperson_list,
        )
    ])
app = dash.Dash()
app.layout = html.Div([
    dcc.Graph(figure=fig)
])

app.run_server(debug=True, use_reloader=False)

In the VSCode browser, go the the Main Menu icon on the far left at the top. Go to Terminal and Choose New Terminal. Ports. In the Terminal Window, go to the Ports tab. Find Port 8080, right click, and choose "Open In Browser" to view the dashboard. 

![Ports View](../images/ports.png)

![Open In Browser](../images/open-in-browser.png)

Below is an image of the dashboard.
![Example Dashbaord](../images/dashboard-example.png)